/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "timer.h"
#include "leds.h"
#include "uart.h"
#include "adc.h"

#if 0  //SJ - disable warning.
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#endif

int main(void)
{
	clock_config();
	leds_init();
	timebase_init();
    uart3_tx_init();

    pc0_adc1_init();

    uint32_t sensor_value = 0;

	/* Loop forever */
	for(;;)
	{
		printf("SJ.. leds on\r\n");
		led_on(RED_LED);
		led_on(GREEN_LED);
		led_on(BLUE_LED);

		sensor_value = adc1_get_data();

		delay_ms(1000);

		led_off(RED_LED);
		led_off(GREEN_LED);
		led_off(BLUE_LED);
		printf("SJ.. leds off\r\n");
		delay_ms(1000);
	}
}
